#!/bin/bash
#Script OrangKuatSabahanterkini
read -p "Username : " Login
read -p "Penambahan Masa Aktif (hari): " masaaktif
mati="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"

chage -E `date -d "$masaaktif days" +"%Y-%m-%d"` $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"

echo -e "--------------------------------"
echo -e "Akun Sudah Diperpanjang Hingga $exp"
echo -e "==========================="
echo -e "Script by \e[1;33;44m OrangKuatSabahanTerkini \e[0m"
